### ISSUE TITLE
use-drag-resize

### ISSUE THREAD

**Issue by honggiang17tb** [plantain-00/composable-editor-canvas#1]
#### Actual:
I use use-drag-resize and when I resize with direction left or left-top or left-bottom until it cannot resize anymore, it automatically moves the element. When I use centerScaling I get the same error but it happens in all directions

**Comment by plantain-00** [comment]
I can't reproduce your issue, can you reproduce it here: [https://plantain-00.github.io/composable-editor-canvas/?p=drag-resize.story](https://plantain-00.github.io/composable-editor-canvas/?p=drag-resize.story)

**Comment by honggiang17tb** [comment]
https://github.com/user-attachments/assets/05217eed-aaf9-4605-a57b-bb43226fb745

This is the problem I encountered

**Comment by plantain-00** [comment]
It can be fixed by adding `transformOffset` option, for example: https://github.com/plantain-00/composable-editor-canvas/commit/5edbd017de2ddd28271c7a8b2ab3e272c4346b83

**Comment by honggiang17tb** [comment]
thanks bro <3
